name: Android CI

on:
  pull_request:
    branches: [ master, main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: fortum/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: |
       ./gradlew build
